sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - motif

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=sox -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y motif

after_failure:
    - pip uninstall -y motif